### PR TITLE
[build] Fix and test karaf-cxf-rest quickstart

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
[merge]

**Comment by grgrzybek** [comment]
[retest] please

**Comment by jamesnetherton** [comment]
[merge]

**Comment by grgrzybek** [comment]
[merge]

**Comment by grgrzybek** [comment]
[retest]

**Comment by jamesnetherton** [comment]
[merge]

**Comment by grgrzybek** [comment]
[merge]

**Comment by grgrzybek** [comment]
[merge]

**Pull request merged**
